### ISSUE TITLE
Hello, the link of pre training model is invalid.

### ISSUE THREAD

**Issue by zwb170010** [Visual-Attention-Network/SegNeXt#10]

**Comment by uyzhang** [comment]
Hello, which model is wrong? Can you tell me more about it?

**Comment by zwb170010** [comment]
> Hello, which model is wrong? Can you tell me more about it?

The repository contains official Pytorch implementations of training and evaluation codes and pre-trained models for [SegNext](https://github.com/Visual-Attention-Network/SegNeXt/blob/main).

**Comment by uyzhang** [comment]
ImageNet Pre-trained models can be found in [TsingHua Cloud](https://cloud.tsinghua.edu.cn/d/c15b25a6745946618462/).

**Comment by zwb170010** [comment]
> ImageNet Pre-trained models can be found in [TsingHua Cloud](https://cloud.tsinghua.edu.cn/d/c15b25a6745946618462/).

Thanks.
