### ISSUE TITLE
about the ade20k dataset config file in SegNeXt

### ISSUE THREAD

**Issue by go-ahead-maker** [Visual-Attention-Network/SegNeXt#14]
Hi, I got a question about the ADE20K dataset used in SegNeXt
The config file of ADE20K dataset in this repo has some differences from the original version in mmseg, e.g., `dict(type='ResizeToMultiple', size_divisor=32),` in transforms, and
```
        type='RepeatDataset',
        times=50,
``` 
I'm new of mmseg, could you explain these different of configs? Thanks a lot.

**Comment by MengzhangLI** [comment]
SegNeXt follows the setting of SegFormer, SegFormer follows this setting on PVT.

The difference between `xxx` and `xxx_repeat` is not very large: https://github.com/NVlabs/SegFormer/issues/27
