### ISSUE TITLE
Hello, can you support binary segmentation dataset? 0 or 255(eg: Medical Image Segmentation)

### ISSUE THREAD

**Issue by zwb170010** [Visual-Attention-Network/SegNeXt#15]

**Comment by MenghaoGuo** [comment]
Yes, we have plan to expand our model for medical image segmentation.

**Comment by zwb170010** [comment]
> Yes, we have plan to expand our model for medical image segmentation.

Is the current git not supported? I tried to process the medical image, but I encountered some problems when calculating the loss.

**Comment by uyzhang** [comment]
You can convert 255 to 1, and then perform a secondary classification. It should also be effective.

**Comment by zwb170010** [comment]
> You can convert 255 to 1, and then perform binary classification. It should also be effective.

Thanks.
