### ISSUE TITLE
Are params really exact?

### ISSUE THREAD

**Issue by Monkey0806** [Visual-Attention-Network/SegNeXt#17]
The params which you exhibit in the tables are 4M, 14M, 28M, 49M (T, S, B, L).But the size of pertained models in the "TsingHua Cloud"  are about 50, 168, 322, 543 MB(T, S, B, L).
      I think the size of pretrained model should equal to (params  x  4B), because one parameter saved as a float32 number which occupy 4 Bytes in memory. So the parameters inferred from pertained models should be **12M, 44M, 80M, 134M.**
     Maybe I misunderstand the rules of memory calculation by params. **Or could you explain?**

**Comment by uyzhang** [comment]
The pertained models in the "TsingHua Cloud" have other information. You can get params using some tools like torchprofile, and can read the code to get details of calculation
<img width="714" alt="截屏2022-10-16 15 30 10" src="https://user-images.githubusercontent.com/26193836/196023759-5a7800ef-e14f-4df9-996a-1f46b0023635.png">

**Comment by Monkey0806** [comment]
Thanks for your reply.I just checked the size of 'state_dict', which size actually matches the params.
