### ISSUE TITLE
Contribute to mmsegmentation

### ISSUE THREAD

**Issue by FabianSchuetze** [Visual-Attention-Network/SegNeXt#18]
Hello, thanks for the wonderful work, I learned a lot from it.

Would you be interesting in contributing your work to mmsegmentation? If you want, I could also help with it.

**Comment by MenghaoGuo** [comment]
Yes, we want to merge segnext into mmsegmentation. 

Do you want to do it together ？

**Comment by FabianSchuetze** [comment]
That is wonderful! I'm looking forward to seeing your work as part of mmsegmentation. 

No, no, you can do it. I didn't want to take away any work from you, I just wanted to offer help in case you are too busy or had other plans.

**Comment by MenghaoGuo** [comment]
Thanks. 

Merging SegNeXt into mmsegmentation is our plan. However, we do not start to do it now. 
If you are interested in getting it done, you are welcome.  
Our team will provide as much help and details as possible if you're going to do it. 

Best,
Menghao

**Comment by FabianSchuetze** [comment]
So then, I'd love to give it a try! I will notify you once there is a PR ready.

**Comment by MenghaoGuo** [comment]
OK, thanks.
