### ISSUE TITLE
about the command of training： ./tools/dist_train.sh /path/to/config 8

### ISSUE THREAD

**Issue by Onehundred0906** [Visual-Attention-Network/SegNeXt#19]
Hello, very appreciate to give us so excellent article to  solve visual tasks, can you explain the path parameter? I cant't  find some information about it in code, very grateful！
![segnext_config](https://user-images.githubusercontent.com/111262872/196072685-74aefb47-2f65-4bb4-81b1-beb4e34b5ea8.jpg)

**Comment by uyzhang** [comment]
For example: ```./tools/dist_train.sh local_configs/segnext/tiny/segnext.tiny.512x512.ade.160k.py 8```

**Comment by Onehundred0906** [comment]
Thanks, i have another question, my computer has only a gpu, your test command is normal to use or not ? i  change the command :./tools/dist_test.sh /path/to/config /path/to/checkpoint_file 1 --eval mIoU. only "8" is instead of "1". I run it but occur some mistakes.

**Comment by uyzhang** [comment]
Because a single GPU cannot use dist_test.sh
