### ISSUE TITLE
MSCAN-Large's e.r or mlp_ratios needs to fix

### ISSUE THREAD

**Issue by saicoco** [Visual-Attention-Network/SegNeXt#2]
https://github.com/Visual-Attention-Network/SegNeXt/blob/1e51c8ac5b94907d915346d5c0e998093d97aa93/mmseg/models/backbones/mscan.py#L175

It will raise size mismatch when load mscan-large reference mscan-large-config

**Comment by saicoco** [comment]
mlp_raitos=[8, 8, 4, 4]

**Comment by uyzhang** [comment]
We write the mlp_raitos parameter in https://github.com/Visual-Attention-Network/SegNeXt/blob/main/local_configs/_base_/models/mscan.py#L10

**Comment by saicoco** [comment]
Thanks to reply, I just  miss it
