### ISSUE TITLE
The code implementation does not match the picture in the paper

### ISSUE THREAD

**Issue by pb585** [Visual-Attention-Network/SegNeXt#22]
Thank you for your job,  I have a question about code. In backbones/mscan.py file, there is a "shortcut" operation in SpatialAttention module but there is a "drop_path" in Block module, It should work the same as “shortcut”。 The first shortcut operation I didn't find in the paper。

**Comment by MenghaoGuo** [comment]
We follow the setting of VAN :  https://arxiv.org/pdf/2202.09741.pdf. 
Here is a trick in VAN experiment, I do not know whether it is important in segnext.
