### ISSUE TITLE
 WARNING - The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by Yaoxingtian** [Visual-Attention-Network/SegNeXt#23]
你好:
我使用的是segnext_tiny_512x512_ade_160k.pth，以及配置文件segnext.tiny.512x512.ade.160k.py，训练的时候有警告 WARNING - The model and loaded state dict do not match exactly，用small模型也是一样的警告。
请问模型是有什么问题吗？ 谢谢

**Comment by uyzhang** [comment]
Because some parameters of the pretrained model do not need to be used.
