### ISSUE TITLE
Why are the results of Mit's Params not consistent with the results presented in the paper, Segformer?

### ISSUE THREAD

**Issue by HuCaoFighting** [Visual-Attention-Network/SegNeXt#24]
![image](https://user-images.githubusercontent.com/37317664/196438552-c66146b3-f740-470a-99d5-958ca4eec1ab.png)
![image](https://user-images.githubusercontent.com/37317664/196438629-e0dc32ae-b888-4ff4-9fe7-54a0e6fd3cd3.png)

**Comment by MenghaoGuo** [comment]
The params of mit is not presented in table 1.
It is presented in Table 7, which is in the supplementary.  


<img width="495" alt="image" src="https://user-images.githubusercontent.com/38318671/196449108-f8ee6758-b0c7-4da9-ab1b-d636aa9d5e9e.png">

Classification head's param is ignored in the segformer encoder.

**Comment by HuCaoFighting** [comment]
OK, I have checked it. The authors updated the arXiv version, which is not consistent with the neurips version.

**Comment by HuCaoFighting** [comment]
I have another question. If using torchprofile to calculate the Transformer-based GFLOPs, do I need to add the extra GFLOPs computation of self-attention?

**Comment by MenghaoGuo** [comment]
If you use torchprofile , you do not need to add extra GFLOPs computation of self-attention.
