### ISSUE TITLE
about the inference speed

### ISSUE THREAD

**Issue by Onehundred0906** [Visual-Attention-Network/SegNeXt#27]
Hello, i use image_demo.py to inference a picture, and the inference time is 0.6+s, can you help explain? thanks! maybe my
gpu and cpu are the main cause?
![2022-10-19 14-38-32屏幕截图](https://user-images.githubusercontent.com/111262872/196888858-7a7076be-98b4-48e4-b03c-5344b512dd68.png)
![Screenshot 2022-10-20 155216](https://user-images.githubusercontent.com/111262872/196889450-f478b3b7-1a11-450f-931d-e2aae97bc134.jpg)

**Comment by MenghaoGuo** [comment]
There are many reasons that can cause your problem.

1. Only 1 img in the inference process will make the speed slow a lot.  The forward time for the entire dataset should be tested and divided by the number of images.
2. Different hardware
3. Different config such as image size. 

Please check the various details carefully
