### ISSUE TITLE
About multi-scale branch

### ISSUE THREAD

**Issue by go-ahead-maker** [Visual-Attention-Network/SegNeXt#28]
Hi authors,
In MSCA, the learned multi-scale features are aggregated via **adding** opt rather than **concatenating**. Is this for the purpose of achieving a better trade-off between performance and complexity? (concat may be more expensive in terms of GPU memory or slower speed).

**Comment by MenghaoGuo** [comment]
We find add can achieve a satisfactory result and do not try to use concat operation. If you are interested in it, you can have a try. Of course, concat requires more paramters and computation.
