### ISSUE TITLE
about train？

### ISSUE THREAD

**Issue by Onehundred0906** [Visual-Attention-Network/SegNeXt#29]
i train my own datasets, and download the pretrained_weights of 'mscan_b.pth', can you explain to put the weights_file to which place? Thanks very much! my command is : python  /tools/train.py local_configs/segnext/base/segnext.base.512x512.tusimple.160k.py  --load-from pretrained/mscan_b.pth 

but occur some error which is showed in the follow picture!
![2022-10-25 13-46-35屏幕截图](https://user-images.githubusercontent.com/111262872/197692918-291b3d00-95ed-4176-a3bf-30bd02effc36.png)

**Comment by uyzhang** [comment]
You need to put the pre-trained weight under the corresponding folder.

**Comment by uyzhang** [comment]
> You need to put the pre-trained weight under the corresponding folder.

And You need to load the pre-trained weight by changing local_configs/segnext/base/segnext.base.512x512.tusimple.160k.py like other configs.

**Comment by Onehundred0906** [comment]
i change the weight's path in code of' local_configs/segnext/base/segnext.base.512x512.tusimple.160k.py' like the first picture, 
![Screenshot 2022-10-25 155929](https://user-images.githubusercontent.com/111262872/197717489-df681b99-12ef-4e46-8ac6-b7286f56bf24.jpg)
but when i train my dataset, the result is showed like the second picture , is very Irregular. emmm, thank you very much for bothering you for my question ！
![2022-10-25 15-22-26屏幕截图](https://user-images.githubusercontent.com/111262872/197718559-e1b6027f-4c50-46e4-86c0-134aed5b2243.png)

**Comment by Onehundred0906** [comment]
my data has only 2 classes(background and road_line), in my opinion, the dataset_config should be correct! thanks very much.

**Comment by Onehundred0906** [comment]
ooo, thanks, maybe this is a cause, but if i need to consider the background based the dataset ade20k, and i can modify where code ?

**Comment by Onehundred0906** [comment]
thanks   i have found the error   and   it has been trained normally, the reduce_zero_label should be False in my dataset config
