### ISSUE TITLE
ImageNet pretrainning configurations

### ISSUE THREAD

**Issue by rayleizhu** [Visual-Attention-Network/SegNeXt#33]
Hi, can you provide ImageNet pretraining configs (e.g. resolution, epochs, training tricks)? They are important for a fair comparison.

**Comment by MenghaoGuo** [comment]
Hi, SegNeXt follows VAN for ImageNet pretrain.

Please refer to [this repo](https://github.com/Visual-Attention-Network/VAN-Classification).

**Comment by rayleizhu** [comment]
> Hi, SegNeXt follows VAN for ImageNet pretrain.
> 
> Please refer to [this repo](https://github.com/Visual-Attention-Network/VAN-Classification).

This is still vague. For example, VAN has both 224 resolution pretraining and 386 resolution pretraining. I think the best way is to provide training scripts as done by [HRViT](https://github.com/facebookresearch/HRViT/blob/main/train.sh)

**Comment by MenghaoGuo** [comment]
For VAN, it only uses 224 resolution for pretraining, which is same with MSCAN.

**Comment by zeyadmahmoudd** [comment]
@rayleizhu have you figured it out?
