### ISSUE TITLE
Cannot reproduce your results

### ISSUE THREAD

**Issue by il1um** [Visual-Attention-Network/SegNeXt#36]
hi，i'm sorry to bother you but 
when i use your local_config(default setting) to train neither using cityscape nor ade20k can reproduce your results. Do you have any idea about this?

When i directly use the pretrained .pth file that you provide，i can get the result 79.25%miou on cityscapes. But when I train the model locally, the result is terrible. 

Here is my result :60.7% miou on cityscapes; 18.16%miou on ADE20K

I would be very grateful if you could reply me ASAP.

**Comment by uyzhang** [comment]
Check whether the pre-training weight is loaded into the network.

**Comment by il1um** [comment]
> 

Thank you so much for your quick reply，but in my experiment, with pre-training weight and without pre-training weight can both only get around 18% miou on ADE20K.
(w/o:18.48%; w:18.16%)

here are the questions:
1: how can i check if i really use or don't use the pre-training weight?
2：Is the score of 18.48%miou on ADE20K  normal (correct) if I don't use pre-training weights?

Thanks

**Comment by uyzhang** [comment]
I have not tried not to load the number of points for pre-training model training.

**Comment by uyzhang** [comment]
1. You can check the log to see whether to load it.
2. I did not try not to load the mIoU of the training pre-training model.
