### ISSUE TITLE
problem about train.py 

### ISSUE THREAD

**Issue by jiawen1929** [Visual-Attention-Network/SegNeXt#38]
你好，我用单卡3060用segnext-t模型在ade20k数据集上跑实验，按作者您的原config文件跑的话，爆显存了。我就把samples_per_gpu设置成了4，learning rate还是按照0.00006跑，跑完整个实验下来，最终的输出是
![image](https://user-images.githubusercontent.com/92011326/203459873-84adc66b-7d05-466d-b564-b1058c5e7719.png)
mIoU只有14.64是啥情况呀，我需要再调整什么吗？感谢协助！

**Comment by uyzhang** [comment]
需要确认一下是否把预训练权重加载进去了

**Comment by jiawen1929** [comment]
好的，你的邮件我已经收到！我会尽快处理，祝你生活顺心。

**Comment by jiawen1929** [comment]
> 你好，是预训练权重加载进去的结构，就是这样吗？
![image](https://user-images.githubusercontent.com/92011326/203460593-131bc470-efb7-443f-a346-4cba787230b1.png)

**Comment by jiawen1929** [comment]
我实验里就是这样设置的

**Comment by uyzhang** [comment]
这个权重文件是下载下来，放在了pretrained文件夹下了吗？能否把实验日志传到issue这。

**Comment by jiawen1929** [comment]
[20221122_000256.log](https://github.com/Visual-Attention-Network/SegNeXt/files/10072553/20221122_000256.log)
非常麻烦您了！

**Comment by jiawen1929** [comment]
为了防止搞错，我在两个路径都放了pretrained文件夹

**Comment by uyzhang** [comment]
还是预训练权重没有加载的问题，你可以再检查一下。
没有用预训练权重的日志：
<img width="588" alt="截屏2022-11-23 11 11 46" src="https://user-images.githubusercontent.com/26193836/203462486-510bfb92-0aaf-4b58-a69d-a602b7a11abc.png">
使用预训练权重的日志：
<img width="631" alt="截屏2022-11-23 11 11 50" src="https://user-images.githubusercontent.com/26193836/203462490-a7dc22a0-bc8e-440c-b709-a69ba99a57d0.png">

**Comment by jiawen1929** [comment]
重新下载了预训练权重文件，重新放置了一遍，成功输出您截图中的‘使用预训练权重的日志’内容了，应该是问题解决了，等实验跑完再看看结果。非常感谢您的耐心解答，祝您paper无限发！！！
