### ISSUE TITLE
KeyError: "EncoderDecoder: 'MSCAN is not in the models registry'"

### ISSUE THREAD

**Issue by EItByTe** [Visual-Attention-Network/SegNeXt#5]
when  I run the train.py, I met with the error.Anyone can help me ...? thanks a lot!  I have checked the register and __init__.py in mmseg/models and mmseg/models/backbones. The MSCAN module should have been registered.

![image](https://user-images.githubusercontent.com/72071163/191767931-1669360c-3b0f-4fb7-a8dd-f6a31db74340.png)

**Comment by uyzhang** [comment]
You should execute this command to install segnext : ```cd SegNeXt``` and ```python setup.py develop```
