### ISSUE TITLE
随机性问题

### ISSUE THREAD

**Issue by bjzhb666** [Visual-Attention-Network/SegNeXt#66]
SegNext中使用的Hamburger head会在测试过程中产生随机性，请问怎么这种随机性会影响算法性能吗？在设计过程中这种随机性对指标的影响怎么样呢？
见[https://github.com/open-mmlab/mmsegmentation/blob/main/mmseg/models/decode_heads/ham_head.py#L119-L126](url)

**Comment by AKAlilghost** [comment]
您好，我在测试过程中也发现了模型的随机性问题，请问这个问题可以解决吗？
