### ISSUE TITLE
Confusing messaging on license: "Apache 2.0" conflicts with "contact for commercial use"

### ISSUE THREAD

**Issue by mbrukman** [Visual-Attention-Network/SegNeXt#7]
_**Disclaimer:** I am not a lawyer and this is not legal advice. Please contact an attorney for any licensing questions, this is just my understanding and is only for informational purposes._

First of all, thank you for publishing your paper and sharing this code!

The License section in the [`README.md`](https://github.com/Visual-Attention-Network/SegNeXt/blob/45f1c441590e458f4fa925afe9dd7213dc5a9b39/README.md) says:

> This repo is under the Apache-2.0 license. For commercial use, please contact the authors.

As you can see in https://choosealicense.com/licenses/apache-2.0/ (created by GitHub), the Apache 2.0 license already allows commercial use:

> **Permissions**
> 
> * Commercial use
> * [...]

and it does not require asking for permission or notifying anyone of commercial use. If you're asking folks to let you know (as an FYI), that's fine, but that would be optional and up to them, and does not belong in the "license" section, as it's not required as part of Apache 2.0 license.

If you want to prevent commercial use without some sort of fee or custom license, then this is not open-source, and Apache 2.0 is perhaps not an appropriate license for your project, so you may want to choose something else, but it may affect who will be able and willing to contribute to a repo that is under a non-open-source license.

In any case, please reach out to an attorney to discuss your questions and your options. As it stands, this is confusing to readers of this project, as "Apache 2.0 license" + "talk to us before commercial use" seems to be conflicting and hence confusing.

Hope this helps.

Best of luck with your project!

**Comment by MenghaoGuo** [comment]
Thank you for your kind reminder, we will carefully learn the differences between these licenses and choose a suitable license to update.

**Comment by mbrukman** [comment]
@MenghaoGuo — you closed the issue, but as far as I can see, there have been no updates to the `README.md` at this time. Would you mind reopening this issue and keeping it open until you resolve this issue?
