### ISSUE TITLE
How do I train a new dataset?

### ISSUE THREAD

**Issue by roystonlmq** [Visual-Attention-Network/SegNeXt#8]
Hi, I have a dataset where I am detecting primarily just one object and I wish to create a mask image of that object. The object would appear white against a black background. 
I have organised it in
SegNeXt/data/
images/
annotations/

Currently your README has the following information for training:
./tools/dist_train.sh /path/to/config 8

Any pretrained models for me to edit and retrain on the new dataset?

**Comment by uyzhang** [comment]
You can refer to [mmseg](https://github.com/open-mmlab/mmsegmentation/blob/v0.24.1/docs/en/tutorials/customize_datasets.md)
