### ISSUE TITLE
Is this model easy to convert to onnx?

### ISSUE THREAD

**Issue by napohou** [Visual-Attention-Network/SegNeXt#9]
thanks!

**Comment by MenghaoGuo** [comment]
This repo is based on mmsegmentaion. 

You can refer to [mmseg](https://mmsegmentation.readthedocs.io/en/latest/) to convert model to onnx.

**Comment by napohou** [comment]
I see. Thanks. I mean do we have any op that onnx does not support?

**Comment by MenghaoGuo** [comment]
I haven't tried to transferSegNeXt to onnx model. 

Segnext has no custom operator, onnx may be able to support it.  I  am not sure.

**Comment by napohou** [comment]
I see. Let me try.
